# Generated by Django 3.0.5 on 2020-04-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_useremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='useremail',
            new_name='email',
        ),
    ]
